[tool.isort]
profile = "django"
line_length = 120
force_single_line = false
combine_as_imports = true
skip = ["migrations", ".venv"]
lines_after_imports = 2

[tool.djlint]
profile = "django"
indent = 2
max_line_length = 120
